### ISSUE TITLE
Question: event loops?

### ISSUE THREAD

**Issue by bbrtj** [Oele/audio-streamgenerator#3]
Hey there,

just a question: would it be possible to have the module slightly reorganized to allow usage of an event loop? I'm not sure how practical would it be, but instead of having a while loop over the main body in `stream` subroutine, we could leave it to the module user to run the code however they like.

The main advantage of the event loop would be the possibility of plugging in pub/sub mechanism to better control the streamer. Currently, it must be done through `run_every_second` subroutines. Since those can't listen, you have to keep checking for a change, which is not practical.

In terms of implementation, we could have a new subroutine which would return an anonymous subroutine that would do exactly what the `while` loop body does now:
```
sub get_streamer {
    # setup variables in this closure
    return sub { ... };
}
```

Then, `stream` subroutine would have to be rewritten to call `get_streamer` and run it in a while loop. To implement an event loop, the module user would use `get_streamer` method to get the subroutine which then would have to be run through the event loop (probably through a very small timeout).

Thoughts?

**Comment by Oele** [comment]
Hi Bartosz, 

I'm so sorry i didn't reply earlier - it's been a busy few weeks. I think your idea is great - I especially think the `run_every_seconds` is a horrible kind of 'API' - I just didn't couldn't really come up with anything better at the time. 

How would you like to approach this? Do you want to implement this? I would be more than happy to accept a pull request, or add you as a maintainer to this project. Or do you think we should further discuss the implementation details first? 

I would be happy to look into this too at some point, but it will probably take a while until i get around to it.. 

Sander

**Comment by bbrtj** [comment]
I can try implementing this, but will be a bit busy in the coming weeks. I guess there's no rush. Will let you know when I'm done.

**Comment by bbrtj** [comment]
Easy implementation in #4. Testing on my VPS, with event loop my radio takes twice as much CPU, but I was expecting that to happen. I run it using this code:

```
use Mojo::IOLoop;

my $loop = Mojo::IOLoop->singleton;

my $streamer_sub = $streamer->get_streamer;
my $wrapper;
$wrapper = sub {
        $streamer_sub->();
        $loop->next_tick($wrapper);
};

$wrapper->();
$loop->start;
```

Old way of streaming still works of course. I'm going to monitor how it behaves and try doing some event watching in the coming days.

Edit: of course, when running the streamer inside the `while` and not an event loop, CPU usage is roughly the same as it was.

**Comment by Oele** [comment]
Am I right in my assumption that you are still experimenting with this? Or is this ready to be merged?

**Comment by bbrtj** [comment]
I had no steam to keep testing it lately. For now I've been monitoring stability / resource usage. Been running nonstop for 55 hours of CPU time and nothing worrying has happened.

I'm just a little worried about my implementation of event loop - since I run a subroutine that sets itself up for the next event loop tick. This looks like taking over the entire event loop. This is why I wanted to set up Redis, Mojo::Redis and some pubsub, as well as web UI with same setup to try controlling the streamer in real time and see if the audio stutters and how responsive it is.

So yeah, need a little more time.

**Comment by bbrtj** [comment]
I have tested pubsub. `->next_tick` in a loop takes over the event loop as I expected - redis does not listen.
`$loop->recurring(0 => $streamer_sub);` does not produce continous audio. I have to figure out other way to run the streamer in a loop that would work and also let redis listen.

**Comment by bbrtj** [comment]
Okay, the following seems to give acceptable results (responds to my clicks within a couple of seconds):
```
$loop->recurring(0.1 => sub {
    for (1 .. 100000) {
        $streamer_sub->();
    }
});
```

So it is possible to implement as I envisioned it, but it requires more effort than I thought. Each function call produces a very tiny fraction of a stream, so it has to be run a lot more than I thought. 

A little bonus though: resource usage is back where it was before.

The merge request may be merged, but I'm not sure how to document this... my way of running it seems more like a hack than an actual solution.

**Comment by Oele** [comment]
Yes, as far as I remember it's essentially processing one sample on each loop, and (depending on your configuration) there are about 44k a second of those. 

Can't we move that `for` loop to the `streamer_sub` or some helper method in the module? 

So you could do something like
```
$loop->recurring(0.1 => sub {
    $streamer_sub->(100000);
});
```

**Comment by Oele** [comment]
Btw, I would have to really dive into the code again to really answer this question, but couldn't it be benificial to change the streamer sub in such a way that it operates on larger chunks of samples at once? Like 10 or 44k on each loop? And only do per-sample processing things while actually mixing? 

It would mean fewer loops, and fewer calls to `read` and `print`, which I suspect might lower resource usage?

**Comment by bbrtj** [comment]
> Btw, I would have to really dive into the code again to really answer this question, but couldn't it be benificial to change the streamer sub in such a way that it operates on larger chunks of samples at once? Like 10 or 44k on each loop? And only do per-sample processing things while actually mixing?
> 
> It would mean fewer loops, and fewer calls to `read` and `print`, which I suspect might lower resource usage?

Yes, I don't fully understand how the streamer processes what it reads from ffmpeg, but it would be awesome if we could have larger chunks. Fewer loops is fewer instructions, so lower resource usage is also to be expected.

I will look into this in the near future. If you want to release to CPAN shortly, don't wait for it to get resolved, as this is highly experimental (now even more than before)

**Comment by bbrtj** [comment]
I got quite far with my implementation of sample batches: see https://github.com/bbrtj/audio-streamgenerator/blob/experiments/lib/Audio/StreamGenerator.pm#L208. It currently uses batches in size of sample_rate (so one second at a time). It generates stable audio with just much fewer iterations, and the resource usage dropped on my VPN to just 3-4% cpu, which is about as much as ffmpeg takes.

However, the cross-fading code is quite arcane to me, and when the song is about to end, the entire thing just hangs with 0% CPU usage indefinetly. It seems to correctly handle skipping though.

Another problem is now that it doesn't work sample-by-sample anymore, the run_every_second API will not work correctly, and the current if statement for it will not work at all. Not sure if it's something that should be fixed or just replaced. If we add a new configuration option, let's say `seconds_per_iteration`, people should be able to have their own APIs centered around calling the streamer sub (even if they don't use an event loop).

Would you be able to provide help refactoring the mixing code? Identifying the separate pieces and moving them to their own methods would help a great deal. I can do this myself, but it will probably take me a long time.

**Comment by Oele** [comment]
Great, sounds like you made a lot of progress already! 

I will definitely take a look at this once I find the time, and i'll try to add some comments to the crossfading part to explain what's happening exaclty, and split out at least the crossfading stuff in a separate sub from the main loop. 

In case you are going to look at it before I do: since you say that 'skipping' works, this means that crossfading by itself is still working fine. So my guess is that there is something in the non-crossfading logic that is preventing the crossfading code from being fired at the right moment. Maybe a blocking read() call that is just hanging, or maybe the crossfading logic is being called, but not exactly in the state that it expects (with `normal_fade_seconds` seconds of audio from the old source on top of my head). Or maybe `$eof` is not true. Or something along those lines.

**Comment by Oele** [comment]
I think I managed to fix it: https://github.com/Oele/audio-streamgenerator/blob/splas/fix-xfade/lib/Audio/StreamGenerator.pm

The main issue was that _get_samples was always returning 1, so $eof was never being set.

**Comment by Oele** [comment]
I have now also moved the mixing stuff to a separate sub and i've added comments explaining the logic, in the same branch. Let me know what you think :)

**Comment by Oele** [comment]
I restructured most of the mixer code too - replaced a lot of the loops that were going on with splice calls. I get the impression that it's working a lot more efficient now.

**Comment by bbrtj** [comment]
Thanks, you did a lot of work! I also made so many mistakes that it puzzles me it even ran in the first place :)

I will make some additions, test and update the pull request. If it works well then I think it will be ready to be merged.

**Comment by bbrtj** [comment]
I added some more commits that, among other things, add an option to specify how much a streamer subroutine should progress the stream. By default, each call produces one second of audio (as it was before).

Works stable on my VPN. With 0.25 seconds on each sub call, CPU usage is 5-6%. Been playing for 3 hours without any issues.

Take a look at my recent changes. If they seem fine, you can go ahead and merge them.
