### ISSUE TITLE
Controlling the logger?

### ISSUE THREAD

**Issue by bbrtj** [Oele/audio-streamgenerator#5]
Sorry if this question is stupid, I'm not very familiar with Log4perl, but seems like Audio::StreamGenerator gives very little control over its logging.

It produces enormous logfiles on my machine (up to 2 gigs). It seems to always initialize with $DEBUG, and Log4perl documentation says it should only be initialized once, and further initializations will replace current config.

If I wanted to control internal logs of StreamGenerator, how should I do it?

**Comment by bbrtj** [comment]
I guess the problem is that those logs are not very useful outside of development, but are still captured by default if you put the system behind something like Ubic.

**Comment by Oele** [comment]
tbh, I haven't really given it much thought - I just wanted to get rid of all the `print STDERR` stuff in there that I was using during initial development, without completely getting rid of any form of logging that might be useful in the future. And i've probably done it wrong. Please feel free to replace it with something that makes more sense, or else i'll try to look at it once I find a bit more time for this thing.

**Comment by Oele** [comment]
Looking at this question again with a bit more time and attention - I think the whole concept between these kinds of (Log4j[ava] inspired) frameworks is, that each logging message has a 'log level' (like, ERROR, WARN, INFO, DEBUG, TRACE). 

The user then specifies which log level (and above) they want to see and where those messages should go. In production, you may want to write ERROR and WARN to an error log, and ignore INFO, or write it to a the application log. During development, you may want to dump all those to STDOUT, and even include DEBUG or TRACE there too, if you really want to dive deep into the inner workings of the code. 

So, i think the 2 problems with our module right now are: 

1) everything has the same log level (INFO) 

and

2) we offer no way for the user to specify what the log level should be, or even better, to freely provide their own Log4Perl configuration, allowing them to direct one level to a file, one to /dev/null and have another generate sms text messages or whatever they prefer. 

Should be fairly easy to improve this situation - we could by default have the current "everything to stdout/stderr(?)" aproach, but give the option in the constructor to override that behaviour by providing a path to a Log4perl configuration file, or whatever other mechanisms Log4perl provides for that purpose. Maybe we could even let the user just pass an initialised Log::Log4perl::Logger, so they can reuse the same one as the rest of the application is using. 

The hardest part is to decide which log messages should have which log level ;) but I suspect you might have already been able to formulate an opinion about this by looking at your huge log files ;) 

What do you think?

**Comment by bbrtj** [comment]
The following may sound revolutionary, sorry for that.

From the current list of `$logger` uses, none of them seem particularly helpful to me:
- `->logcarp` calls in the constructor should most likely be just `Carp::croak` calls - I see no value added by Log4perl here
- the rest of the `->info` calls seem to mostly help when debugging the mixing mechanism or other stuff that are abstracted away from the module user. Those has always been working flawlessly for me, so I had no use for them yet

It might be that those `->info` calls could be replaced by those `print STDERR` you removed earlier (nothing wrong with those actually) and the dependency could be dropped - which is very good. Those prints should just be in their own method, so they can be easily replaced.

For example, after adding a new `debug` option to the constructor:

```
sub debug {
  my ($self, $message) = @_;
  return unless $self->{debug};
  print STDERR $message . "\n";
}

# later

$self->debug("mixing second $full_second...");
```

If someone wanted to build their own special logging (Log::Log4perl / Log::Dispatch or anything else) they can just extend the class and reintroduce the `debug` method. I think it would be better, because if you really need to use a logging system, then you probably don't want to mix them, and then we shouldn't force Log::Log4perl on those who already use something else.

But also...

During analyzing this, I found what the real problem is - either ffmpeg command (passed to `out_fh` or taken from `get_new_source`) output is captured from STDERR by my daemonizer and put into logfiles (I think the actual Log4perl logs may be there somewhere, but they are shadowed by ffmpeg logs), and this output is very verbose. I should look into this more: which command produces most of this output and what I can do from my usercode to reduce this.

**Comment by Oele** [comment]
Yes, I think that makes a lot of sense, good idea!

Regarding ffmpeg - you may want to look into its `-loglevel` option.

**Comment by Oele** [comment]
What do you think of this: https://github.com/Oele/audio-streamgenerator/pull/6

**Comment by bbrtj** [comment]
Looks good, I left a single comment. Debug functions are probably a good choice, easier to customize than extending the class. I thought about them earlier, but I have to restrain myself from using anonymous functions or it gets out of hand quickly.

**Comment by Oele** [comment]
Thank you.!Fixed that & merged.
