### ISSUE TITLE
README.md generation

### ISSUE THREAD

**Issue by bbrtj** [Oele/audio-streamgenerator#7]
Hey, I've noticed you set up a script to generate README.md from lib/Audio/StreamGenerator.pm (pod to markdown translator).

Since this is manual work, I would like to suggest no-maintenance alternatives:

- if `.md` format is not a must, you can separate lib/Audio/StreamGenerator.pod from lib/Audio/StreamGenerator.pm and symlink README.pod to it. Github will view `.pod` just fine, but MakeMaker might tell you that some old versions can mistreat README.pod
- if you don't really need duplicated documentation, you can set up a friendly generic README.md that point people to stuff like metacpan and bugtracker. This is what I do for my repos, see https://github.com/bbrtj/perl-form-tiny/blob/master/README.md

I think the second option is more flexible. As a plus, git history will be more clear without readme re-generation commits.

**Comment by Oele** [comment]
Wow, I didn't know Github could parse .pod. But I think the second option is fine indeed. Some (somewhat related) questions that come up now i'm looking at this:
- May I add you as an author? 
- I seem to have chosen the FreeBSD license when I first created the package, but I don't really have a strong preference. I see that your module is using the perl license, which I think may be more appropriate. What do you think?
- I never followed up on the discussion about MIN_PERL_VERSION we had in https://github.com/Oele/audio-streamgenerator/pull/2 . I will set it to 5.10 as you suggested back then, unless you see any problem with that? 
- Do you have any ideas/advice around the version number of the module itself? It's on 0.06 now, which is probably a bit silly. I guess i just set it to 1.00 and then increment to 1.01, 1.02 etc until a major rewrite or breaking change happens? 

Sorry for all the silly questions - I have 0 experience with this stuff :))

**Comment by bbrtj** [comment]
> * May I add you as an author?

Sure ;) I don't mind helping out if it will increase the quality.

> * I seem to have chosen the FreeBSD license when I first created the package, but I don't really have a strong preference. I see that your module is using the perl license, which I think may be more appropriate. What do you think?

I think BSD 2-clause is a very nice license. I tend to choose perl license from pure laziness, but there has been some voice against it in the community lately. If I was to relicense my modules, it would be to BSD2.

> * I never followed up on the discussion about MIN_PERL_VERSION we had in https://github.com/Oele/audio-streamgenerator/pull/2 . I will set it to 5.10 as you suggested back then, unless you see any problem with that?

There should be no problem at all. All the module's code seems to be 5.10-compatible, and I find it a good version to base CPAN modules on.

> * Do you have any ideas/advice around the version number of the module itself? It's on 0.06 now, which is probably a bit silly. I guess i just set it to 1.00 and then increment to 1.01, 1.02 etc until a major rewrite or breaking change happens?

That's what I do, and many other modules as well (like Moo or Type::Tiny).

Many modules don't do that, maybe even a majority, so it's not uncommon if you just continue with 0.07, 0.08 etc. I think it's good practice to mark stable release with 1.00 and then continue from there as you explained.

**Comment by Oele** [comment]
Great! :) 

Does this look right to you then? 

https://github.com/Oele/audio-streamgenerator/pull/8
